ui: mocha-bdd
server: "./test/server.js"
scripts:
  - "https://s3.amazonaws.com/es6-promises/promise-1.0.0.min.js"
  - "lib/client.js"
browsers:
  - name: chrome
    version: 29..latest
    platform: Linux
  - name: firefox
    version: 29..latest
    platform: Linux
  - name: safari
    version: 5..7
  - name: ie
    version: 8..latest
  - name: android
    version: latest
# - name: opera
#   version: latest
#   platform: Linux
#  - name: iphone
#    version: 6.0..latest
